// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_2._0.Migrations
{
    [DbContext(typeof(GarageVehicleContext))]
    [Migration("20220220094150_AddedParkingSpotsEntity")]
    partial class AddedParkingSpotsEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Garage_2._0.Models.Member", b =>
                {
                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MembershipId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocialSecurityNumber");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("Garage_2._0.Models.MemberHasMembership", b =>
                {
                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MembershipId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MemberId", "MembershipId");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("MemberHasMembership");
                });

            modelBuilder.Entity("Garage_2._0.Models.Membership", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("BenefitBase")
                        .HasColumnType("float");

                    b.Property<double>("BenefitHourly")
                        .HasColumnType("float");

                    b.HasKey("Type");

                    b.ToTable("Membership");
                });

            modelBuilder.Entity("Garage_2._0.Models.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("VehicleLicense")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleLicense");

                    b.ToTable("ParkinSpot");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true
                        },
                        new
                        {
                            Id = 2,
                            Available = true
                        },
                        new
                        {
                            Id = 3,
                            Available = true
                        },
                        new
                        {
                            Id = 4,
                            Available = true
                        },
                        new
                        {
                            Id = 5,
                            Available = true
                        },
                        new
                        {
                            Id = 6,
                            Available = true
                        },
                        new
                        {
                            Id = 7,
                            Available = true
                        },
                        new
                        {
                            Id = 8,
                            Available = true
                        },
                        new
                        {
                            Id = 9,
                            Available = true
                        },
                        new
                        {
                            Id = 10,
                            Available = true
                        },
                        new
                        {
                            Id = 11,
                            Available = true
                        },
                        new
                        {
                            Id = 12,
                            Available = true
                        },
                        new
                        {
                            Id = 13,
                            Available = true
                        },
                        new
                        {
                            Id = 14,
                            Available = true
                        },
                        new
                        {
                            Id = 15,
                            Available = true
                        },
                        new
                        {
                            Id = 16,
                            Available = true
                        },
                        new
                        {
                            Id = 17,
                            Available = true
                        },
                        new
                        {
                            Id = 18,
                            Available = true
                        },
                        new
                        {
                            Id = 19,
                            Available = true
                        },
                        new
                        {
                            Id = 20,
                            Available = true
                        },
                        new
                        {
                            Id = 21,
                            Available = true
                        },
                        new
                        {
                            Id = 22,
                            Available = true
                        },
                        new
                        {
                            Id = 23,
                            Available = true
                        },
                        new
                        {
                            Id = 24,
                            Available = true
                        },
                        new
                        {
                            Id = 25,
                            Available = true
                        },
                        new
                        {
                            Id = 26,
                            Available = true
                        },
                        new
                        {
                            Id = 27,
                            Available = true
                        },
                        new
                        {
                            Id = 28,
                            Available = true
                        },
                        new
                        {
                            Id = 29,
                            Available = true
                        },
                        new
                        {
                            Id = 30,
                            Available = true
                        });
                });

            modelBuilder.Entity("Garage_2._0.Models.Vehicle", b =>
                {
                    b.Property<string>("License")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ParkingSpot")
                        .HasColumnType("int");

                    b.Property<string>("VehicleTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Wheels")
                        .HasColumnType("int");

                    b.HasKey("License");

                    b.HasIndex("MemberId");

                    b.HasIndex("VehicleTypeName");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("Garage_2._0.Models.VehicleType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("VehicleType");
                });

            modelBuilder.Entity("Garage_2._0.Models.Member", b =>
                {
                    b.OwnsOne("Garage_2._0.Models.Name", "Name", b1 =>
                        {
                            b1.Property<string>("MemberSocialSecurityNumber")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LastName");

                            b1.HasKey("MemberSocialSecurityNumber");

                            b1.ToTable("Member");

                            b1.WithOwner()
                                .HasForeignKey("MemberSocialSecurityNumber");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Garage_2._0.Models.MemberHasMembership", b =>
                {
                    b.HasOne("Garage_2._0.Models.Member", null)
                        .WithOne("Membership")
                        .HasForeignKey("Garage_2._0.Models.MemberHasMembership", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Garage_2._0.Models.ParkingSpot", b =>
                {
                    b.HasOne("Garage_2._0.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleLicense");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Garage_2._0.Models.Vehicle", b =>
                {
                    b.HasOne("Garage_2._0.Models.Member", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Garage_2._0.Models.VehicleType", "Type")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleTypeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Garage_2._0.Models.Member", b =>
                {
                    b.Navigation("Membership");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Garage_2._0.Models.VehicleType", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
