// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_2._0.Migrations
{
    [DbContext(typeof(GarageVehicleContext))]
    [Migration("20220215144055_membersInit")]
    partial class membersInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Garage_2._0.Models.Member", b =>
                {
                    b.Property<string>("SocialSecurityNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SocialSecurityNumber");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("Garage_2._0.Models.Vehicle", b =>
                {
                    b.Property<string>("License")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ParkingSpot")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Wheels")
                        .HasColumnType("int");

                    b.Property<string>("ownerSocialSecurityNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("License");

                    b.HasIndex("ownerSocialSecurityNumber");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            License = "EGW123",
                            Arrival = new DateTime(2022, 2, 1, 12, 9, 28, 0, DateTimeKind.Unspecified),
                            Color = "Red",
                            Make = "Volvo",
                            Model = "Xc60",
                            ParkingSpot = 1,
                            Type = 0,
                            Wheels = 4
                        },
                        new
                        {
                            License = "ASL123",
                            Arrival = new DateTime(2022, 2, 1, 13, 9, 28, 0, DateTimeKind.Unspecified),
                            Color = "White",
                            Make = "Volvo",
                            Model = "Xc60",
                            ParkingSpot = 2,
                            Type = 0,
                            Wheels = 4
                        },
                        new
                        {
                            License = "MXP123",
                            Arrival = new DateTime(2022, 2, 1, 14, 9, 28, 0, DateTimeKind.Unspecified),
                            Color = "Yellow",
                            Make = "Volvo",
                            Model = "Xc60",
                            ParkingSpot = 3,
                            Type = 2,
                            Wheels = 2
                        },
                        new
                        {
                            License = "RRH123",
                            Arrival = new DateTime(2022, 2, 1, 15, 9, 28, 0, DateTimeKind.Unspecified),
                            Color = "Blue",
                            Make = "Volvo",
                            Model = "Xc60",
                            ParkingSpot = 4,
                            Type = 1,
                            Wheels = 8
                        });
                });

            modelBuilder.Entity("Garage_2._0.Models.Member", b =>
                {
                    b.OwnsOne("Garage_2._0.Models.Name", "Name", b1 =>
                        {
                            b1.Property<string>("MemberSocialSecurityNumber")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LastName");

                            b1.HasKey("MemberSocialSecurityNumber");

                            b1.ToTable("Member");

                            b1.WithOwner()
                                .HasForeignKey("MemberSocialSecurityNumber");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Garage_2._0.Models.Vehicle", b =>
                {
                    b.HasOne("Garage_2._0.Models.Member", "owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("ownerSocialSecurityNumber");

                    b.Navigation("owner");
                });

            modelBuilder.Entity("Garage_2._0.Models.Member", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
